// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Rpmd_rD4Itsyr8EM5J5mc1dvHzV5QNc',
    appId: '1:1004994470673:web:4c2653f0bf1cecba42a2b0',
    messagingSenderId: '1004994470673',
    projectId: 'sakura-simulation',
    authDomain: 'sakura-simulation.firebaseapp.com',
    storageBucket: 'sakura-simulation.appspot.com',
    measurementId: 'G-BWET93H78R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfkQiuc-vK6gCx4ZqEnDvx2407TjB-U1U',
    appId: '1:1004994470673:android:9dc558074edac01242a2b0',
    messagingSenderId: '1004994470673',
    projectId: 'sakura-simulation',
    storageBucket: 'sakura-simulation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtI5osOR3AvMG-cirfw9VCgd_3VsUgOIA',
    appId: '1:1004994470673:ios:41a69e9175e89a5542a2b0',
    messagingSenderId: '1004994470673',
    projectId: 'sakura-simulation',
    storageBucket: 'sakura-simulation.appspot.com',
    iosClientId: '1004994470673-7t75ejl944pu32p8rojuumtl9rlhb7c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakuraSimulation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtI5osOR3AvMG-cirfw9VCgd_3VsUgOIA',
    appId: '1:1004994470673:ios:41a69e9175e89a5542a2b0',
    messagingSenderId: '1004994470673',
    projectId: 'sakura-simulation',
    storageBucket: 'sakura-simulation.appspot.com',
    iosClientId: '1004994470673-7t75ejl944pu32p8rojuumtl9rlhb7c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakuraSimulation',
  );
}
